
spring:
  application:
    name: flex-imdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb;MODE=DB2;INIT=RUNSCRIPT FROM 'src/main/resources/schema.sql';
    username: sa
    password: sa

  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    url: /public/flex-imdb.yml
server:
  servlet:
    context-path: /flex-imdb/api/